server:
  port: 8082

spring:
  application:
    name: ms-citas

  datasource:
    url: jdbc:mysql://localhost:3306/pontebella_citas?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: America/Bogota

app:
  ms-usuarios:
    base-url: http://localhost:8081

logging:
  level:
    com.pontebella.mscitas: DEBUG
